netdev-dpdk-vdpa: ---TBD--- disable rte_eth_vhost_get_queue_event
In DPDK 20.11, compiling has an error of:
with shared complains about:
/images/elibr/dpdk/build/../drivers/net/vhost/rte_eth_vhost.c:1663:
undefined reference to `rte_vdev_register'

Disable the call to `rte_eth_vhost_get_queue_event' avoids it.
DPDK pc files may be changed to resolve it. Meanwhile disable this call.

Issue: 2316924
Change-Id: I4b95a877f743f617cfa02cae26f889daef2c2d4c
Signed-off-by: Eli Britstein <elibr@nvidia.com>