netdev-offload-dpdk: Fix build warning about operator precedence
The following warning is issued with clang:
   lib/netdev-offload-dpdk.c:4126:42: \
      error: operator '?:' has lower precedence than '+'; \
      '+' will be evaluated first [-Werror,-Wparentheses]

Make the operation priorities explicit.

Issue: 2317149
Change-Id: Ie3c87c4e16a61a60f25115cf3a93dd5fcb8c8734
Fixes: d078569f5175 ("netdev-offload-dpdk: Add support for geneve header
decap offload")
Signed-off-by: Gaetan Rivet <grive@u256.net>