netdev-linux: fix compile error in nl_msg_put_act_police
Use 'memset' to init memory to 0.

This resolves a build problem with clang on Ubuntu 16.04 on ARM (in Travis):

libtool: compile:  clang -DHAVE_CONFIG_H -I. -I ./include -I ./include
-I ./lib -I ./lib -Wstrict-prototypes -Wall -Wextra -Wno-sign-compare
-Wpointer-arith -Wformat -Wformat-security -Wswitch-enum
-Wunused-parameter -Wbad-function-cast -Wcast-align
-Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes
-Wmissing-field-initializers -Wthread-safety -fno-strict-aliasing
-Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument
-Wshift-negative-value -Qunused-arguments -Wshadow
-Warray-bounds-pointer-arithmetic -Werror -Werror -g -O2
-Wno-error=unused-command-line-argument -DHAVE_AVX512F -MT
lib/netlink-conntrack.lo -MD -MP -MF lib/.deps/netlink-conntrack.Tpo
-c lib/netlink-conntrack.c -o lib/netlink-conntrack.o
lib/netdev-linux.c:2638:38: error: missing field 'action' initializer
[-Werror,-Wmissing-field-initializers]
    struct tc_police null_police = {0};
                                     ^
1 error generated.
make[2]: *** [lib/netdev-linux.lo] Error 1
make[2]: *** Waiting for unfinished jobs....

Issue: 2802102
Fixes: c2567e533 ("add port-based ingress policing based packet-per-second rate-limiting")
Change-Id: Ib835cdf4ee6c7d382b8d5ea34155c6de7313332b
Reported-by: David Marchand <david.marchand@redhat.com>
Signed-off-by: Yong Xu <yong.xu@corigine.com>
Signed-off-by: Simon Horman <simon.horman@netronome.com>