netdev-offload-dpdk: Fix build warning in per-thread-xrealloc
lib/netdev-offload-dpdk.c: In function ‘create_pre_post_ct’:
lib/netdev-offload-dpdk.c:123:36: error: ‘new_p’ may be used
uninitialized in this function [-Werror=maybe-uninitialized]
  123 |     if (!salloc_contains(pt->s, p) || new_p == NULL) {
      |                                    ^
lib/netdev-offload-dpdk.c:117:11: note: ‘new_p’ was declared here
  117 |     void *new_p;
      |           ^~~~~

Issue: 2688338
Change-Id: Id2f0e82b196d2b8b7cfa28cba7c43125e461427a
Fixes: 2c03eafe1333 ("netdev-offload-dpdk: Failover to malloc if salloc fails")
Signed-off-by: Gaetan Rivet <grive@u256.net>